
kibot:
  version: 1

preflight:
  check_zone_fills: true
  
outputs:
  - name: "gerbers"
    comment: "Gerbers for production"
    type: gerber
    dir: kibot/gerber
    options:
      subtract_mask_from_silk: true
    layers:
      - "selected"

  - name: "gerber-drill"
    comment: "Drill positions for production"
    type: "gerb_drill"
    dir: kibot/gerber

  - name: "gerber-compressed"
    comment: "compressing the gerbers into one convenient file"
    type: compress
    dir: kibot
    options:
      files:
        - from_output: "gerbers"
          dest: /
        - from_output: "gerber-drill"
          dest: /
  - name: "bom-csv"
    type: "bom"
    dir: kibot/bom
    options:
      format: CSV
      output: '%f_bom.%x'
      columns:
        - field: ITEM_NUMBER
        - field: Reference
        - field: Quantity
        - field: Description
        - field: Package
        - field: Type
        - field: Manufacturer
        - field: "Mfg Part #"
        - field: Substitution
        